#!/bin/sh

DPID=`uci get openflow.@ofswitch[0].dpid`
SNMP_TUNNEL_PORT=6693
OPENFLOW_PORT=6633
CHECK_INTERVAL=10
UNINIT_STRING=' No Such Instance currently exists at this OID'

snmp_extensions=

log () {
	logger [HOMENETS][${DPID}] : $1 
}

 while true; do
 
 	error=0
 	
 	# check if snmp daemon is up.
 	if ! ps aux | grep -v grep | grep snmpd > /dev/null; then
 		log "snmpd is not running - Restarting..."
 		error=1
 		/etc/init.d/snmpd restart
 	fi
 	

	# check if snmp extensions are up.
	ret="$(snmpget -Os -c public -v 2c localhost 1.3.6.1.4.1.8072.1.3.2.2.1.2.\"getmacaddress\" 2> /dev/null | awk -F"=" '{ print $2 }')"
	if [ "$ret" = "$UNINIT_STRING" ]; then
		log "SNMP Extension getmacaddress not set - restarting hmnet..."
		error=1
		/etc/init.d/hmnet restart
	fi
 	
 	# check snmp_tunnel
 	if ! ps aux | grep -v grep | grep snmp_tunnel > /dev/null; then
 		log "snmp_tunnel is not running - Restarting..."
 		error=1
 		/etc/init.d/hmnet restart
 	fi
 	
 	# check ofdatapath
 	if ! ps aux | grep -v grep | grep ofdatapath > /dev/null; then
 		log "ofdatapath is not running - Restarting..."
 		error=1
 		/etc/init.d/openflow restart
 	fi
 	
 	# check ofprotocol
 	if ! ps aux | grep -v grep | grep ofprotocol > /dev/null; then
 		log "ofprotocol is not running - Restarting..."
 		error=1
 		/etc/init.d/openflow restart
 	fi
 	
 	# check if snmp_tunnel is connected
 	if ! netstat -a 2>/dev/null | grep ${SNMP_TUNNEL_PORT} | grep -v localhost | grep ESTABLISHED > /dev/null; then
 		log "snmp_tunnel is not connected..."
 		error=1
 	fi
 	
 	# check if openflow is connected
 	if ! netstat -a 2>/dev/null | grep ${OPENFLOW_PORT} | grep -v localhost | grep ESTABLISHED > /dev/null; then
 		log "openflow protocol is not connected..."
 		error=1
 	fi
 	
 	if [ ${error} -eq 1 ]; then
 		echo 0 > /sys/class/leds/tl-wr1043nd\:green\:qss/brightness
 		log "Check Status...FAIL"
 	else
 		echo 1 > /sys/class/leds/tl-wr1043nd\:green\:qss/brightness
 		log "Check Status...OK"
 	fi
 	
 	# mae sure that uci changes in our config files get applied.
 	# uci commit doesn't seem to work every time...?
	log "Applying Configuration updates"
 	apply_config -a
 	
 	sleep ${CHECK_INTERVAL}
 
 done